### PR TITLE
Use ESP-IDF version from an input

### PR DESCRIPTION
**Pull request by kumekay**
Use an IDF version from job input, 

Because it's not possible to parameterize the docker image with Github Actions YAML syntax, a container with ESP-IDF is launched manually inside a "composite" action

It looks like this way is a bit faster than the current one:

- New approach: **2m 42s** https://github.com/kumekay/test_idf_project/actions/runs/1839836343
- Old approach: **3m 2s** https://github.com/kumekay/test_idf_project/actions/runs/1839836345

### CODE REVIEW

**Comment by kumekay** [comment]
I didn't add target configuration or a other command support here, but it's trivial to add in the next PRs

**Comment by kumekay** [comment]
@dobairoland PTAL

**Comment by tomassebestik** [comment]
@kumekay LGTM Sergei

**Review by tomassebestik — APPROVED** [review]

**Comment by dobairoland** [comment]
LGTM as far as I can tell.

**Comment by kumekay** [comment]
@tomassebestik @dobairoland Thank you for your reviews!

**Comment by kumekay** [comment]
> For some reason, the `latest` version also included the new build process (_run docker inside the step manually_), which confused me.
`espressif/esp-idf-ci-action@latest` uses this tag: https://github.com/espressif/esp-idf-ci-action/blob/latest/action.yml has a Docker file and runs in docker, but unlike `main` it doesn't use  `docker run` shell command but rely on GitHub Actions yml file configuration.

**Pull request merged**
